//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agency()
        {
            this.Users = new HashSet<User>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public long AgencyId { get; set; }
        public string AgencyName { get; set; }
        public string REPName { get; set; }
        public string REPLastName { get; set; }
        public string REPEmail { get; set; }
        public string Company { get; set; }
        public string Password { get; set; }
        public string CountryCode { get; set; }
        public string Phone { get; set; }
        public int AgentType { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public int CommissionPercentage { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Commission Commission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
