//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2bUserAccess
    {
        public long B2bUserAccessId { get; set; }
        public long UserId { get; set; }
        public string ClientToken { get; set; }
        public string APIToken { get; set; }
        public string Clientkey { get; set; }
        public string APIKey { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
