//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deposit()
        {
            this.DepositLogs = new HashSet<DepositLog>();
        }
    
        public long DepositId { get; set; }
        public long UserId { get; set; }
        public long POSId { get; set; }
        public string TransactionId { get; set; }
        public int PaymentType { get; set; }
        public string CheckNumberOrSlipId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> PercentageAmount { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        public string ChequeBankName { get; set; }
        public string NameOnCheque { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int BankAccountId { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<bool> isAudit { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositLog> DepositLogs { get; set; }
        public virtual POS POS { get; set; }
        public virtual User User { get; set; }
    }
}
