//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterRecharge
    {
        public long MeterRechargeId { get; set; }
        public long UserId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<long> MeterId { get; set; }
        public decimal Amount { get; set; }
        public string MeterNumber { get; set; }
        public Nullable<long> POSId { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> PlatFormId { get; set; }
        public string MeterToken { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual POS POS { get; set; }
        public virtual User User { get; set; }
    }
}
