//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Modules1 = new HashSet<Module>();
            this.UserAssignedModules = new HashSet<UserAssignedModule>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ControllerName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> SubMenuOf { get; set; }
    
        public virtual ICollection<Module> Modules1 { get; set; }
        public virtual Module Module1 { get; set; }
        public virtual ICollection<UserAssignedModule> UserAssignedModules { get; set; }
    }
}
