//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationId { get; set; }
        public long UserId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public Nullable<long> RowId { get; set; }
        public bool MarkAsRead { get; set; }
        public System.DateTime SentOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
