//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformTransaction
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int PlatformId { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountPlatform { get; set; }
        public int Status { get; set; }
        public string Beneficiary { get; set; }
        public string UserReference { get; set; }
        public Nullable<int> ApiConnectionId { get; set; }
        public string Currency { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<long> PosId { get; set; }
        public string OperatorReference { get; set; }
        public string PinSerial { get; set; }
        public string PinNumber { get; set; }
        public string PinInstructions { get; set; }
        public string ApiTransactionId { get; set; }
        public long LastPendingCheck { get; set; }
        public long TransactionDetailId { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual PlatformApiConnection PlatformApiConnection { get; set; }
        public virtual POS POS { get; set; }
        public virtual User User { get; set; }
    }
}
