//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platform()
        {
            this.PlatformApiConnections = new HashSet<PlatformApiConnection>();
            this.PlatformPacParams = new HashSet<PlatformPacParam>();
            this.PlatformTransactions = new HashSet<PlatformTransaction>();
        }
    
        public int PlatformId { get; set; }
        public string Title { get; set; }
        public bool IsDeleted { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string ShortName { get; set; }
        public string Logo { get; set; }
        public decimal MinimumAmount { get; set; }
        public bool DisablePlatform { get; set; }
        public string DisabledPlatformMessage { get; set; }
        public int PlatformType { get; set; }
        public Nullable<int> PlatformApiConnId { get; set; }
        public Nullable<int> PlatformApiConnBackupId { get; set; }
    
        public virtual PlatformApiConnection PlatformApiConnection { get; set; }
        public virtual PlatformApiConnection PlatformApiConnection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatformApiConnection> PlatformApiConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatformPacParam> PlatformPacParams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatformTransaction> PlatformTransactions { get; set; }
    }
}
