//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformPacParam
    {
        public int PlatformId { get; set; }
        public int PlatformApiConnectionId { get; set; }
        public string Config { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public long Id { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual PlatformApiConnection PlatformApiConnection { get; set; }
    }
}
