//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        public POS()
        {
            this.Deposits = new HashSet<Deposit>();
            this.MeterRecharges = new HashSet<MeterRecharge>();
            this.POSAssignedPlatforms = new HashSet<POSAssignedPlatform>();
        }
    
        public long POSId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> VendorType { get; set; }
        public string CountryCode { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> CommissionPercentage { get; set; }
        public Nullable<bool> EmailNotificationSales { get; set; }
        public Nullable<bool> EmailNotificationDeposit { get; set; }
        public Nullable<bool> SMSNotificationSales { get; set; }
        public Nullable<bool> SMSNotificationDeposit { get; set; }
    
        public virtual Commission Commission { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<MeterRecharge> MeterRecharges { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<POSAssignedPlatform> POSAssignedPlatforms { get; set; }
    }
}
