//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POS()
        {
            this.Deposits = new HashSet<Deposit>();
            this.PendingDeposits = new HashSet<PendingDeposit>();
            this.POSAssignedPlatforms = new HashSet<POSAssignedPlatform>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.PlatformTransactions = new HashSet<PlatformTransaction>();
        }
    
        public long POSId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> VendorType { get; set; }
        public string CountryCode { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> CommissionPercentage { get; set; }
        public Nullable<bool> EmailNotificationSales { get; set; }
        public Nullable<bool> EmailNotificationDeposit { get; set; }
        public Nullable<bool> SMSNotificationSales { get; set; }
        public Nullable<bool> SMSNotificationDeposit { get; set; }
        public bool IsPassCode { get; set; }
        public string Email { get; set; }
        public string PassCode { get; set; }
        public Nullable<bool> WebSms { get; set; }
        public Nullable<bool> PosSms { get; set; }
        public Nullable<bool> PosPrint { get; set; }
        public Nullable<bool> WebPrint { get; set; }
        public Nullable<bool> WebBarcode { get; set; }
        public Nullable<bool> PosBarcode { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual Commission Commission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposit> Deposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingDeposit> PendingDeposits { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSAssignedPlatform> POSAssignedPlatforms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatformTransaction> PlatformTransactions { get; set; }
    }
}
