//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSAssignedPlatform
    {
        public long AssignPOSPlatformId { get; set; }
        public long POSId { get; set; }
        public int PlatformId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual POS POS { get; set; }
    }
}
