//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_LOG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> POSID { get; set; }
        public string TransactionID { get; set; }
        public string Phone_number { get; set; }
        public string Meter_Number { get; set; }
        public Nullable<long> AgentID { get; set; }
    }
}
