//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temptransactiondetail
    {
        public Nullable<long> Row1_ { get; set; }
        public Nullable<long> Row2_ { get; set; }
        public long TransactionDetailsId { get; set; }
        public long UserId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<long> MeterId { get; set; }
        public decimal Amount { get; set; }
        public decimal CurrentVendorBalance { get; set; }
        public Nullable<long> POSId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
