//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAssignedModule
    {
        public long AssignUserModuleId { get; set; }
        public long UserId { get; set; }
        public int ModuleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
