//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAssignedWidget
    {
        public long AssignWidgetId { get; set; }
        public long UserId { get; set; }
        public int WidgetId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<bool> IsAddedFromAgency { get; set; }
    
        public virtual User User { get; set; }
    }
}
