//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSchedule
    {
        public int UserScheduleId { get; set; }
        public long UserId { get; set; }
        public int ScheduleType { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Balance { get; set; }
    }
}
