//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public long VendorId { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Vendor1 { get; set; }
        public string Email { get; set; }
        public long AgencyId { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AgentType { get; set; }
        public Nullable<int> CommissionPercentage { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
